### ISSUE TITLE
GLA Quad Cannon doubles DPS when vet 1 and becomes weaker when scrapped and vetted

### ISSUE THREAD

**Issue by commy2** [TheSuperHackers/GeneralsGamePatch#56]
The current behaviour of the Quad is best summed up in this picture:

![https://i.imgur.com/DSOJdrb.png](https://i.imgur.com/DSOJdrb.png)

I propse we change the veterancy bonuses of the Quad to make them align with all other units, and make scrapping them up a small bonus on every veterancy level.

**Comment by xezon** [comment]
Please investigate the damage values across veterancy, scrap & co. Maybe this can be fixed and tweaked in a meaningful way where Quad overall keeps same strength in early and late game.

**Comment by ReLaX82** [comment]
Nice Summery, horrible to See.

Shall I make a Proposal?

**Comment by commy2** [comment]
One "easy" to implement fix is to overwrite the Rate Of Fire veterancy bonuses for the Quad Cannon and to instead slightly increase the Damage veterancy bonuses to roughly match what the ROF would do in a game with more simulation steps per time unit.

See: https://github.com/commy2/zerohour/commit/b253b897c26f7fd71978e5478d59a594c56189e3
Also see: https://github.com/commy2/zerohour/commit/e7a0d3f1a27bea4c4bb9c5b19ac74c05fcec7802

**Comment by Generalcamo** [comment]
Be extremely careful with that proposal. Both the mods C&C Shockwave and ROTR did fix this issue by using the "intended" values as you propose, however it turned out to radically boost the quad's damage to insane levels. We ended up having to perform an approximately 25% cut on the salvage damage levels as compared to the ZH "intended" level. Likely this was never caught during quality assurance testing, therefore the balance was never actually properly finished here. 

For reference for those not in the know: the bug itself is caused by the rate of fire being tied to frame rate; in a 30FPS match (the standard for multiplayer), it is technically impossible to have a delay between shots (DBS) that is less than 33.333 (which is rounded up to 66ms). The first salvage upgrade brings the quad cannon to a DBS of 50, which is rounded to 66; this is the absolute minimum value that is possible, therefore the second salvage level does nothing (and due to the first salvage level having less damage than no salvage at all, a single veterancy level that brings the quad to the absolute minimum DBS means that the salvage level would cause it to do less DPS)

**Comment by Jundiyy** [comment]
Whilst it would be nice to fix, I know mods have but with different values (even as mentioned above) this would have devistating effects on gameplay. GLA Quads would be so much more powerful and GLA itself would be.
If we lower damage values for less vetted/'scrapped' this would weaken GLA. So it causes problems whichever way it is fixed.

**Comment by commy2** [comment]
The current behavior also has devastating effects on gameplay.

> Be extremely careful with that proposal. Both the mods C&C Shockwave and ROTR did fix this issue by using the "intended" values as you propose, however it turned out to radically boost the quad's damage to insane levels.

I did not propose the "intended" values by EA. It's obvious to anyone that they break the game. In fact, I did not propose any values, just a technical way to apply yet unspecified values.

**Comment by xezon** [comment]
The least I would suggest doing is to not nerf the Quad at all when scrapping up. OR reversing the model: No Scrap has the big gun, and when scrapping up the gun gets smaller. It's stupid, but at least its readable. So this would then help discourage players to drive with Quat over scraps.

**Comment by xezon** [comment]
I put together some values that are still close to original but swapped and more reasonable. Unscrapped damage is still close to the original damage. And scrap gets small buffs until max damage output is reached. If Quad kills ground units then there will always be something to pickup and quad can be scrapped up. Problem: Air enemies. There is no scrap from Air units so vetted quads will not reach max potential vs Air as opposed to the original.
```
      No Scrap    Scrap +1    Scrap +2
Vet0    +0          +40         +80
Vet1    +80         +100        +120
Vet2    +100        +120        +140
Vet3    +120        +140        +160
```

We could also shift damage to say Quad is weaker with no scrap, but also stronger with max scrap.
```
      No Scrap    Scrap +1    Scrap +2
Vet0    +0          +40         +80
Vet1    +100        +120        +140
Vet2    +120        +140        +160
Vet3    +140        +160        +180
```

Next is a reasonable approach. Scrap up just does nothing.
```
      No Scrap    Scrap +1    Scrap +2
Vet0    +0          +60         +60
Vet1    +120        +120        +120
Vet2    +140        +140        +140
Vet3    +160        +160        +160
```

We could also reduce Vet0 Scrap Damage a bit to compensate for the fact that we keep benefits at Vet1:
```
      No Scrap    Scrap +1    Scrap +2
Vet0    +0          +30         +30
Vet1    +120        +120        +120
Vet2    +140        +140        +140
Vet3    +160        +160        +160
```

**Comment by xezon** [comment]
Going forward, I would suggest to come up with the most logical approach that is suitable, implement and then test and review this by playing pro matches. We can always revert back to original if it changes gameplay too much.

**Comment by ZekeDlyoung** [comment]
How about keeping the quads insane damage bonus as EA intended, but changing the damage type to GATTLING?

Or make it similar to the technical? Only scrap weapons would be changed to have GATTLING damage, so the player chooses whether you want quads to stay "good vs everything" (since full vet no salvage quad gives the most DPS anyway), or if the player is willing to get the extra damage but make it specialized against infantry and aircraft only

**Comment by Jundiyy** [comment]
Reducing non scrapped quad damage must be a no go, that would change gameplay a lot.
Scrapped Quads...Its difficult to say, making GLA quada even more powerful than they are, would once again change gameplay but not as much as not scrapped change. 
This would end up requiring a massive amount of test games from top players to see what would be best. 
I do like the approach of just changing the model to show if it's more or less.

**Comment by xezon** [comment]
The values I suggested above did not factor in the fact that Scrap also has a chance to increase the Veterancy level of the unit. **At which chance does a scrap increase veterancy for Quad?** With this information we may be able to estimate a better rebalance of damage values.

**Comment by Stubbjax** [comment]
These are the chances according to `Crate.ini`:

```
WeaponChance = 100%
LevelChance = 25%
MoneyChance = 75%
```

Which translates to a 100% chance of a weapon upgrade if not fully scrapped, and then a 25% chance to rank up if not heroic.

**Comment by xezon** [comment]
Hmm ok in that case the Scrap Vet Up influence is negligible.

**Comment by Jundiyy** [comment]
I would prefer to keep original no vetted unit stats the same and also not vetted + scrap.
The others could have a very minimal to know increase.

Or

Have non scrapped Quads have very slightly lower damage. Scrap one does the damage of the 1.04 not scrapped Quad and then scrap 2 does a tiny bit more.
So for example using the first post, vet 1 would be 115, scrap veg 1 would be 120 and double scrap vet 1 would be 125. This would keep Quads nearly at the same level as they originally are. Although would need to test to see if it's too much of a change.

**Comment by xezon** [comment]
@Jundiyy that would be table 3 or 4 I posted previously.

**Comment by Jundiyy** [comment]
Ah yes, so table 3 would be no change at all, which seems reasonable.

Table 4 weakens scrapped but non vetted Quads? If so, rather not do that.
I suppose my version was slightly different
Although I think table 3 is good.

**Comment by commy2** [comment]
I feel like keeping +120% @ vet 1, which is an absoluetly insane buff compared to any other upgrade in the game, is the wrong direction to go. Vetted Quads will still be able to delete buildings and tanks alike in seconds. 
Just focusing on the scrap levels does not address the elephant in the room. All this change (table 1-4) would effectively do is to buff the Quad. Hard to sell a patch when it buffs the Quad, instead of make it so players are rewarded fo keeping units alive longer (and also picking up scrap).

**Comment by commy2** [comment]
For comparision and to put actual numbers into this discussion, for normal units that do not fire at the simultation frame limit of the game, the bonuses from vet 1 are +20% Rate of Fire and +10% Damage, which totals to roughly +32% DPS due to the cummulative nature.

+32% compared to +120%

That's 4 times as much for the Quad, and a real issue with the game.

Edit: and just to put this into more context, at vet 3, non bugged units gain +60% Rate of Fire and +30% Damage, which adds up to +108% DPS. ...which is still less than a Quad at vet 1 lol

**Comment by xezon** [comment]
@Jundiyy I have to correct myself. Table 2 refers to what you wrote before.
@commy2 Vetted Quads are very strong indeed. I think even when nerfing they are still very strong. But such strong unit is needed for GLA, because it allows to kill humvees and chinooks which are hard to kill with unvetted quads.

**Comment by Jundiyy** [comment]
Ah yes, thank you. That table is similar to what I proposed yes. Although I'd prefer a smaller change to keep the feel more normal.

**Comment by RisingZH** [comment]
I definitely wouldn't change unvetted + unscrapped quads, would be too difficult to balance.

Table 3 seems like the easiest to implement and least controversial, makes no sense for quads to get weaker with scrap.

I do like the idea of table 1 but this would fall more into the category of a  balance change than a bug fix and would require a lot of testing.

**Comment by ExiLe-ZH** [comment]
I feel as long as the base quad doesn't change, everything should be fine. Vetted quad always rather been overpowered and GLA never relied on those. That's why I think there's some room to subtly tweak the numbers, here an example:

```
      No Scrap    Scrap +1    Scrap +2
Vet0    +0          +50         +70
Vet1    +120        +130        +140
Vet2    +130        +140        +150
Vet3    +140        +150        +160
```

I feel that table 3 of xezon has more negative impact on the game than this one, because in practice you don't see ppl avoiding scraps in the middle of battles. That means statistically the Quad performance is not as good as the non-scrap numbers indicate. Table 3 is a buff that GLA does not need.

**Comment by MTKing4** [comment]
Table 1 by far the best of the 4 tables

Or this

> That's why I think there's some room to subtly tweak the numbers, here an example:
![Screenshot_20210910-163824_Chrome](https://user-images.githubusercontent.com/83613147/132862176-f91c1068-0c55-4767-9d11-9d97d94fe134.jpg)

**Comment by ExiLe-ZH** [comment]
Add in the reason that you always should scrap your nonvetted quads anyway because it’s a fast and reliable way of making many quads have 60% extra damage output. You’re not skipping that because potential veterancy without scraps will be better. That’s stupid because you want to have as much firepower as possible for the very next engagement.

**Comment by Stubbjax** [comment]
If players aren't already aware of the relatively large negative impact of scrapping quads, then they are certainly not likely to notice minor adjustments to the base damage values (apparently as much as ~50%).

However, if players _are_ aware of the issue _and collect the scrap anyway_, then they are essentially accepting the damage reduction and thus should accept damage / balance adjustments to compensate this being fixed.

Conversely, if players are aware of the issue and _actively avoid_ collecting scrap because of it, then you have a fundamental flaw that detracts from gameplay and should be fixed.

**Comment by MTKing4** [comment]
Even when they know and actively trying to not take the scrap, it still happens by accident a whole lot of times by experts themselves, so yeah it should be fixed

**Comment by Madrageeeeee** [comment]
if you dont want to change the game dynamics and dont want to increase gla strength i think it is a difficult puzzle.

What you could do is perhaps:
- scrapped quads that get promoted revert back to their original form so they do get a benefit from being promoted (and they had the benefit of being scrapped while it lasted)
- Vetted quads can not get scrapped and can only get promotion or money from scraps

This would maintain the game dynamics but it would remove a micro element / element to excel.

And gla doesnt really need the buff that this gives it. You can also just not scrap your quads and scrap scorps techs instead. Or decide to scrap non vetted quads for the extra firepower. 

I think messing with quads will really affect gameplay since it is such a core unit of the game / for gla and people expect it to behave a certain way.

**Comment by ZekeDlyoung** [comment]
I think we should just go with vetted quads simply do not lose or gain damage with scrap and just see how people react.

Or just make a poll

**Comment by xezon** [comment]
I am not sure if a Survey is appropriate for this, because this issue goes beyond personal preference. Maybe we are overthinking this instead of play testing it.

**Comment by ExiLe-ZH** [comment]
We might be overthinking this indeed.

lets just test different models.

I predict though that buff models affect the game in a more negative way than the models that slightly nerf the speed at which quads gain extra firepower.

**Comment by xezon** [comment]
How about we do this:

Unscrapped will have 20 pts less firepower, but with scraps it will get to where original Quad without scrap was. Impact is likely minimal. As for Quad vs Humvee I estimate it would cause just a 1 or 2 frame difference in kill speed, which is rather miniscule. On the other hand scrapped Quad would perform much better against Humvee, so GLA should be happy with this.

```
      No Scrap    Scrap +1    Scrap +2
Vet0    +0          +40         +80
Vet1    +100        +110        +120
Vet2    +120        +130        +140
Vet3    +140        +150        +160
```

If someone can post armor of humvee and base damage of Quad, then we can calculate kill frame difference exact.

**Comment by ExiLe-ZH** [comment]
> How about we do this:
> 
> Unscrapped will have 20 pts less firepower, but with scraps it will get to where original Quad without scrap was. Impact is likely minimal. As for Quad vs Humvee I estimate it would cause just a 1 or 2 frame difference in kill speed, which is rather miniscule. On the other hand scrapped Quad would perform much better against Humvee, so GLA should be happy with this.
> 
> ```
>       No Scrap    Scrap +1    Scrap +2
> Vet0    +0          +40         +80
> Vet1    +100        +110        +120
> Vet2    +120        +130        +140
> Vet3    +140        +150        +160
> ```
> 
> If someone can post armor of humvee and base damage of Quad, then we can calculate kill frame difference exact.

Yes we can try this. 

I also want to try another model that isn’t mentioned here yet. So after having thought this over a bit more, things might play out differently than we think.

 ```
      No Scrap    Scrap +1    Scrap +2
Vet0    +0         +60         +76
Vet1    +76        +92         +120
Vet2    +92        +116        +140
Vet3    +108       +134        +160
 ```
 
This one reverses the original model and improves scrap 1 to sit in between. Yes, no scrap is less powerful, but any scrapped state is stronger across the board (except single scrap vet 0, which remains the same).


_My theory:_
Despite the powerloss of scraps in 1.04, scrapped quads still seem to dominate the most, especially in gla mirrors. I’ve analyzed this a bit watching multiple replays.

So in most battles only a few quads vet up, but the rest doesn’t, why wouldn’t you take the 60% scrap boost on the other quads to steamroll the enemy in the very next offense?

Well you probably always should and that doesn’t change with this new model, in fact, taking scraps will be even better.

---------------------------------------------
This is the reason why I think the “non damage loss models” might actually proof to be a huge unwanted buff.
---------------------------------------------
We should try all these different model approaches anyhow, cause just theory isn’t sufficient.

**Comment by commy2** [comment]
Implemented two possible solutions mentioned in this thread. __exact values may change__:

"Make Scrap do nothing after vet 1 solution":

https://github.com/xezon/GeneralsGamePatch/pull/358

Generic veterancy solution or "make Quad vet up like other units":

https://github.com/xezon/GeneralsGamePatch/pull/359

**Comment by Jundiyy** [comment]
I think anything that makes the original Quad weaker with/without scrap is a bad thing, the original value is very important. 
They are the most used Quads in the game so to make them weaker would start changing balance and would need testing vs all armies with many many games.

I would prefer table 3, would save test problems as Rising has said.
Otherwise this (mentioned above) is close to what looks okay.
```
      No Scrap    Scrap +1    Scrap +2
Vet0    +0          +40         +80
Vet1    +100        +110        +120
Vet2    +120        +130        +140
Vet3    +140        +150        +160
```
This seems reasonable but I would still prefer the Vet0 Scrap 1 to be closer to the original, maybe a 50. I think a smaller change would be better.

If we can't go with table 3, perhaps this will be better. It does make the Quads slightly weaker and then slightly better.
```
      No Scrap    Scrap +1    Scrap +2
Vet0    +0          +55         +60
Vet1    +115        +120        +125
Vet2    +135        +140        +145
Vet3    +155        +160        +165
```
Or even less of a change. 
```
      No Scrap    Scrap +1    Scrap +2
Vet0    +0          +57         +60
Vet1    +117        +120        +123
Vet2    +137        +140        +143
Vet3    +157        +160        +163
```
But what also Rage said is very important.

**Comment by commy2** [comment]
Changes below 5% would be pointless, as that wouldn't change how much hits any of the units take to kill. May as well change nothing then.

Edit: think about it. A unit would have to eat 33 hits before death for 3% to make up 0.99 additional hits, which is, for the Quad, literally 2 frames or 0.06 seconds.

**Comment by xezon** [comment]
Related test branches:
* #358
* #359

**Comment by ReLaX82** [comment]
I think just looking "quite" over these numbers cant be the result.

In work I also do some calculations and so I did here.
I think we need to think about the occurance of vetted quads. Maybe it gives in Theory a better picture. 

I am just trying to tackle and understand the topic better. Just have a Look, I included 3 examples. Also we can add boundaries or other circumstances.

[https://www.gamereplays.org/community/index.php?act=Attach&type=post&id=873955](https://www.gamereplays.org/community/index.php?act=Attach&type=post&id=873955)

**Comment by ReLaX82** [comment]
In order to investigate how much % of each Quad is moving around as an overview I made this topic
--> https://www.gamereplays.org/community/index.php?showtopic=1059670

Post 11 contains a massive amount of replays which might be of use.

You can make a evaluation out of these reaplys.

As long as this scrap deny point is treated like it has been I will not further support here.

ReLaX

**Comment by xezon** [comment]
I was wondering why @Jundiyy would insist on not changing the damage output of non-scrapped Quads, because in a regular battle environment there would be a fair distributions of Scrap Crates to pick up and get the damage output levels increased. However, that assumes a ground war scenario. For Quads vs air units the assumption falls flat and GLA would be hurt with nerfed No Scrap quads against air attacks. Most notably against attacks from USA Airforce, which can amass planes and helicopters, which leave no scrap to pick up when shot down.

Without this air battle consideration, I do find @ImTimK suggestion reasonable. Essentially inverting the damage on scrap levels and scaling the middle scrap value would give the Quad an overall almost identical pool of damage. No scrap and level 1 scrap could be tweaked a bit, but starting point is this:

## Inverted & Scaled
```
      No Scrap    Scrap +1    Scrap +2     DMG Sum    DMG Sum Diff
Vet0    +0          +60         +60          120          +0
Vet1    +76         +98        +120          294          +22
Vet2    +92        +116        +140          348          +24
Vet3    +108       +134        +160          402          +26
```

## Original
```
      No Scrap    Scrap +1    Scrap +2     DMG Sum
Vet0    +0          +60         +60          120
Vet1    +120        +76         +76          272
Vet2    +140        +92         +92          324
Vet3    +160        +108        +108         376
```

Unfortunately we cannot just do that because of the chance of pure air battles.

**Comment by xezon** [comment]
In regards to boosting GLA anti air, there is still this option, but it is not for Early game and thus no replacement for weaker quads.

* #298

**Comment by xezon** [comment]
Right now I think that there is no clever solution to change this and make guarantees that it plays fairly. This however would assume that it was fair originally to begin with. The only approach I can think of here is to simply initiate a trial run. Submit something that looks reasonable on paper, and then observe whether or not we end up with cool GLA fights in this project. Maybe it plays ok, then we can tweak it further if so required. And in the worst case we just revert it to what it was originally.

I propose the following values:

## Inverted & Scaled Buff
```
      No Scrap    Scrap +1    Scrap +2     DMG Sum    DMG Sum Diff
Vet0      +0         +60         +60         120          +0
Vet1     +80        +100        +120         300          +28
Vet2    +100        +120        +140         360          +36
Vet3    +120        +140        +160         420          +44
```

When we change DPS in test patch, I suggest to not specify how we changed it. We can just let users play and wait for unbiased feedback.

**Comment by ExiLe-ZH** [comment]
> Right now I think that there is no clever solution to change this and make guarantees that it plays fairly. This however would assume that it was fair originally to begin with. The only approach I can think of here is to simply initiate a trial run. Submit something that looks reasonable on paper, and then observe whether or not we end up with cool GLA fights in this project. Maybe it plays ok, then we can tweak it further if so required. And in the worst case we just revert it to what it was originally.
> 
> I propose the following values:
> ## Inverted & Scaled Buff
> 
> ```
>       No Scrap    Scrap +1    Scrap +2     DMG Sum    DMG Sum Diff
> Vet0      +0         +60         +60         120          +0
> Vet1     +80        +100        +120         300          +28
> Vet2    +100        +120        +140         360          +36
> Vet3    +120        +140        +160         420          +44
> ```
> 
> When we change DPS in test patch, I suggest to not specify how we changed it. We can just let users play and wait for unbiased feedback.

I think this is a good model to test first. 

For ground battles I think it plays out positively overall, it would take a little longer for Quads to become insanely powerful, but it's probably a minor justified nerf since GLA is usually a bit too successful with the mindless Quad spam vs a number of factions (China's mainly).

For air battle matchups, this change would probably play out positive vs China's going Lixes/Migs, as it allows a few more errors from the China player without GLA obtaining super overpowered quads too easily. 

Only vs Air it might play out negatively though, because Comanches are quite a bit better than Lixes and it's not always easy for GLA to have enough firepower. And as you mentioned yourself, scraps are non-obtainable vs pure Commiespam whereas China's usually combine air with ground.

**Comment by xezon** [comment]
Original

DelayBetweenShots 25 equals 66
DelayBetweenShots 50 equals 66
DelayBetweenShots 100 equals 133
DelayBetweenShots 200 equals 200

## GameData.ini
```
  WeaponBonus = VETERAN  RATE_OF_FIRE  120%
  WeaponBonus = VETERAN  DAMAGE        110%
  WeaponBonus = ELITE    RATE_OF_FIRE  140%
  WeaponBonus = ELITE    DAMAGE        120%
  WeaponBonus = HERO     RATE_OF_FIRE  160%
  WeaponBonus = HERO     DAMAGE        130%
```

## Weapon.ini
```
Weapon QuadCannonGun
  PrimaryDamage         = 10.0
  DelayBetweenShots     = 100 ; is 133
  WeaponBonus           = PLAYER_UPGRADE DAMAGE 125%
End

Weapon QuadCannonGunAir
  PrimaryDamage         = 5.0
  DelayBetweenShots     = 100 ; is 133
  WeaponBonus           = PLAYER_UPGRADE DAMAGE 125%
End

Weapon QuadCannonGunUpgradeOne
  PrimaryDamage         = 8.0
  DelayBetweenShots     = 50 ; is 66
  WeaponBonus           = PLAYER_UPGRADE DAMAGE 125%
End

Weapon QuadCannonGunUpgradeOneAir
  PrimaryDamage         = 5.0
  DelayBetweenShots     = 50 ; is 66
  WeaponBonus           = PLAYER_UPGRADE DAMAGE 125%
End

Weapon QuadCannonGunUpgradeTwo
  PrimaryDamage         = 8.0
  DelayBetweenShots     = 25 ; is 66
  WeaponBonus           = PLAYER_UPGRADE DAMAGE 125%
End

Weapon QuadCannonGunUpgradeTwoAir
  PrimaryDamage         = 5.0
  DelayBetweenShots     = 25 ; is 66
  WeaponBonus           = PLAYER_UPGRADE DAMAGE 125%
End
```

Edit: Incorrect calculations redacted.

**Comment by xezon** [comment]
Quad Scrap Veterancy comparison video:

https://www.youtube.com/watch?v=pc8jtTn2_ao

**Comment by EnigmaZift** [comment]
Here are my calculations on the matter, considering how the game runs and all the bonuses.
https://docs.google.com/spreadsheets/d/1DHJviAjbmICpXkhKTD0OfykxS52lgHb5FG6s8uhAD0I/edit?usp=sharing

To TLDR;

The scrap and vet bonuses are working as intended! Except for the final scrap upgrade!

The game has a capped minimum rate of fire - 66.66ms - at which units cannot fire any faster.
The final scrap attempts to reduce the rate of fire from 50ms (which rounds to 66ms) down to 25ms (which also rounds to 66ms)
So there is no bonus from the final scrap.

The best way to get the intended damage output from this scrap would be to double the damage of the final scrap Quad.
However... 

As I'm sure you all know, this would really unbalanced, and they would have most likely caught how broken this would be during testing in the original game, but since it was never programmed in the right way, they never did.

I am actually recommending to you guys not to touch the Quad at all, because it's very dangerous that you might ruin the game.

You can if you want, spread the bonus of the Scrap 1 Quad so that the Scrap 2 Quad gets it instead, and the Scrap 1 Quad gets an in-between value.
This is perfectly fine, although a slight nerf to GLA.

**Comment by EnigmaZift** [comment]
This spreadsheet explains everything:
https://docs.google.com/spreadsheets/d/1DHJviAjbmICpXkhKTD0OfykxS52lgHb5FG6s8uhAD0I/edit#gid=0

The issue is that the original Quad actually did 2.0 more damage than the Scrapped versions, at the cost of half the rate of fire.
However, as the scrap changes the rate of fire, the rate of fire also rounds up to the nearest logic frame.
The second scrap's reduction in rate of fire has no effect because they both round to the same logic frame.

The rate of fire bonus from being veteran allows the Unscrapped Quad to fire at the same rate as the Scrapped Quads. 
Due to the increased raw damage of the Unscrapped Quad, it provides an overall better DPS.

I would be very cautious about how I approached changing the Quad, but there's the full calculation there.

**Comment by xezon** [comment]
[Quad Cannon Stuff.xlsx](https://github.com/TheSuperHackers/GeneralsGamePatch/files/9113184/Quad.Cannon.Stuff.xlsx)

**Comment by xezon** [comment]
Alright. I combined knowledge of Enigma and hanfield and put them into new comprehensive data sheet which shows many stats and all Quad guns.

https://docs.google.com/spreadsheets/d/1aOH2Yp-0NB2H2QS3TGnAQtqDFbZXMZg6

It appears GunAir has the same damage across all veterancies and scraps, so we only need to tweak the regular gun for ground units, which is good news, because that means we don't mess with Quad vs Plane battles.

**Comment by xezon** [comment]
FYI: % values do accept comma:

```c++
float INI::Scan_PercentToReal(const char *token)
{
    float value;
    int res = sscanf(token, "%f", &value);
    captainslog_relassert(res == 1, 0xDEAD0006, "Unable to parse percentage from token %s.", token);

    return (value / 100.0f);
}
```

**Comment by commy2** [comment]
EnigmaZift's spreadsheet contains various errors in the numbers. Just refer to the picture in the OP. It is calculated as well as timed.

**Comment by xezon** [comment]
Please use the spreadsheet in our repo inside Balance folder, not Enigmas. Enigmas spreadsheet helped me to get started, so his effort deserves no flak but praise.

**Comment by xezon** [comment]
https://www.youtube.com/watch?v=gVI1kYzvLuw

Check video. Quad Cannon looks very powerful. Isn't it too strong when vet?

**Comment by xezon** [comment]
Maybe a plain redistribution is fairer.

## Inverted Redist
```
      No Scrap    Scrap +1    Scrap +2     DMG Sum    DMG Sum Diff
Vet0    +0          +60         +60          120          +0
Vet1    +60         +92         +120         272          +0
Vet2    +76         +108        +140         324          +0
Vet3    +92         +124        +160         376          +0
```

## Original
```
      No Scrap    Scrap +1    Scrap +2     DMG Sum
Vet0    +0          +60         +60          120
Vet1    +120        +76         +76          272
Vet2    +140        +92         +92          324
Vet3    +160        +108        +108         376
```

**Comment by ExiLe-ZH** [comment]
> https://www.youtube.com/watch?v=gVI1kYzvLuw
> 
> 
> 
> Check video. Quad Cannon looks very powerful. Isn't it too strong when vet?

Wow yea thats total bs, didn't know it was that bad.

Veterancy damage increments need to be the same as the Gat (what are the exact values?). Where it needs 1 or 2 scraps to match the gat damage output. If we choose for 1 scrap then it has potential to outperform the gat with 2 scraps.

This all can be changed without affecting anti air damage right?

**Comment by xezon** [comment]
Yes, Quad Cannon Anti Air Guns are separate from Ground Guns. The Air Guns also have just moderate bonus with +10%, +20%, +30% for veterancy. I will add Gattling Tank Damage to DPS calculator later and post its values for reference.

**Comment by xezon** [comment]
## China Gatling vs Quad Cannon DPS

You need to primarily look at CONTINUOUS_FIRE_MEAN and CONTINUOUS_FIRE_FAST for Gatling. These are the damages with spun gun. At the bottom you find Gatling VETERAN+CONTINUOUS_FIRE_FAST which can be compared against Quads VETERAN.

![gattling_vs_quad_dps](https://user-images.githubusercontent.com/4720891/180450089-a68e1c20-fddc-4e71-a891-ecdf7d5f91fb.png)


### Observations

* Unscrapped Quad is about **40 dmg points worse** than Gatling at full spin
* VETERAN Unscrapped Quad is about **40 dmg points better** than VETERAN Gatling at full spin
* HERO Unscrapped Quad is about **50 dmg points better** than HERO Gatling at full spin
* VETERAN Unscrapped Quad is about **20 dmg points better** than HERO Gatling at full spin
* VETERAN Scrapped (1) Quad is about **10 dmg points better** VETERAN Gatling at full spin
* HERO Scrapped (1) Quad is about **10 dmg points better** HERO Gatling at full spin
